docker: delivery/gocilla/Dockerfile
jobs:
  environment: env
  build: echo 'Building'
  test-component: echo 'Test component'
  package: echo 'Package'
  publish: echo 'Publish'
  deploy: echo 'Deploy'
  test-e2e: echo 'Test E2E'
pipelines:
  - name: pipeline-pull
    jobs:
      - environment
      - build
      - test-component
  - name: pipeline-ci
    jobs:
      - environment
      - build
      - test-component
      - package
      - publish
      - deploy
  - name: pipeline-pre
    jobs:
      - environment
      - build
      - test-component
      - package
      - publish
      - deploy
      - test-e2e
  - name: pipeline-pro
    jobs:
      - environment
      - deploy
      - test-e2e
